config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { maximum: 50}
  
  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
validates :title, :detail, presence: true
validates :title, length: { maximum: 25 }
validates :detail, length: { maximum: 300}

belongs_to :user
has_many  :comment, dependent: :destroy
has_many :user, through: :favorite
has_one_attached :image

  def self.search(search)
    if search != ""
      Post.where('title LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, :password, :specialize, :experience, :word, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6 }
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}+\z/i }
  validates :word, length: { maximum: 20 }


  has_many :comment
  has_many :post, dependent: :destroy
  has_many :post, through: :favorite
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:specialize,:experience,:word])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      redirect_to "/posts/#{@comment.post.id}"
    else
      # render template: "/posts/#{@comment.post.id}"
      redirect_to "/posts/#{@comment.post.id}"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :before_post, only:  [:show,:destroy,:edit,:update]
  before_action :move_to_index, except: [:index, :show, :serch]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to :root
    else
      render "new"
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comment.includes(:user)
  end

  def destroy
    if @post.destroy
      redirect_to :root
    else
      redirect_to item_path(@post.id)
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      redirect_to edit_post_path(@post.id)
    end
  end

  def search
    @posts = Post.search(params[:keyword])
  end

  private

  def post_params
    params.require(:post).permit(:title,:detail,:image).merge(user_id: current_user.id)
  end

  def before_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Medical Study</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= render "shared/header"%>
編集画面
<%= form_with(model: @post, local: true) do |post| %>
    <%= post.text_field :title, placeholder: "タイトル" %>
    <%= post.text_area :detail, placeholder: "内容" %>
    <%= post.submit "SEND" %>
<% end %>
<%= render "shared/footer" %>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<div class="post-index">投稿一覧</div>
  <div class="post-all">
    <% @posts.each do |post| %>
    <div class="post-top">
      <div class="post-title"><%= post.title %></div>
        <%= image_tag post.image.variant(resize:'200x200'), class: "post-image" if post.image.attached?%>
        <div class="read-article"><%= link_to "記事を読む", post_path(post.id), method: :get %></div>
    </div>
    <% end %>
  </div>
<% if user_signed_in? %>
<div class='post-btn'>
  <%= link_to "投稿する",new_post_path, class: "post-btn-text"%>
</div>
<% end %>
<%= render "shared/footer" %>

app/views/posts/new.html.erb
<%= render "shared/header"%>
<%= render 'shared/error_messages', model: @post %>
<div class="new-post">新規投稿ページ</div>
<%= form_with(model: @post, local: true) do |post| %>
　<label class="form-image">
    <span class="image-file">画像をここから選択する</span>
    <%= post.file_field :image, class: 'hidden' %>
　</label>
  <div class="new-post-title"><%= post.text_field :title, placeholder: "タイトル25文字以内" %></div>
  <div class="new-post-detail"><%= post.text_area :detail, placeholder: "文章300文字以内"%>
  <%= post.submit "SEND" %>
<% end %>
<%= render "shared/footer" %>

app/views/posts/search.html.erb
<%= render "shared/header" %>

<%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "タイトルから記事を検索", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<div class="post-main">
  <div class="post-wrapper">
    <% @posts.each do |post| %>
      <div class="post-top">
        <div class="post-title"><%= post.title %></div>
        <%= image_tag post.image.variant(resize:'200x200'), class: "post-image" if post.image.attached?%>
        <div class="read-article"><%= link_to "記事を読む", post_path(post.id), method: :get %></div>
      </div>
    <% end %>
  </div>
 </div>

<% if user_signed_in? %>
<div class='post-btn'>
  <%= link_to "投稿する",new_post_path, class: "post-btn-text"%>
</div>
<% end %>

<%= render "shared/footer" %>

app/views/posts/show.html.erb
<%= render "shared/header"%>
<div class="show-title"><%= @post.title %></div>
<div class="show-image"><%= image_tag @post.image.variant(resize:'500x750'), class: 'message-image' if @post.image.attached?%></div>
<div class="show-detail"><%= @post.detail %></div>

<div class="user-only">
<% if user_signed_in? && current_user.id == @post.user.id %>
<%= link_to '削除', "/posts/#{@post.id}", method: :delete %>
<%= link_to '編集', edit_post_path(@post.id), method: :get %>
<% end %>
</div>

<div class="comment-form">
  <% if current_user %>
    <%= form_with(model: [@post, @comment], local: true) do |form| %>
      <%= form.text_area :content, placeholder: "質問等を入力", rows: "2" %>
      <%= form.submit "SEND" %>
    <% end %>
  <% else %>
      コメントにはサインインが必要です。
  <% end %>
</div>
<%= render 'shared/error_messages', model: @comment %>
<div class="comment-top">
  <div class="comment-header">＜コメント一覧＞</div>
  <div class="comment-index">
    <% if @comments %>
      <% @comments.each do |comment| %>
        <p class="comment-part">
          <%= comment.user.name %>：<%= comment.content %>
        </p>
      <% end %>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
 <div class="error-alert">
   <ul>
     <% model.errors.full_messages.each do |message| %>
       <li class='error-message'><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>

app/views/shared/_footer.html.erb
    <footer>
      <%= link_to "Medical Study","/", class: "footer-home-link"%>
      <ul class="footer-list">
        <li class="lists"><%= link_to "お問い合わせ","/"%></li>
        <li class="lists"><%= link_to "運営企業","/"%></li>
        <li class="lists"><%= link_to "利用規約","/"%></li>
        <li class="lists"><%= link_to "プライバシーポリシー","/"%></li>
        <li class="lists"><%= link_to "サイトマップ","/"%></li>
      </ul>
      <div class="copyright">Copyright © PT CORPORATION. All Rights Reserved.</div>
    </footer>

app/views/shared/_header-user.html.erb
<header>
      <%= link_to "Medical Study","/", class: "user-home-link"%>
</header>

app/views/shared/_header.html.erb
<header>
      <%= link_to "Medical Study","/", class: "home-link"%>
      <ul class="devise-links" >
        <% if user_signed_in? %>
          <li class="signin-name"><%= current_user.name %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout"  %></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
        <% end %>
      </ul>
</header>